//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTrace
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime TimeSheetIN { get; set; }
        public DateTime? TimeSheetOUT { get; set; }
        public string Status { get; set; }
        public int? TotalHours { get; set; }

        public TimeTrace()
        {

        }
        public TimeTrace(string user,DateTime date, int TimeSheetId, DateTime inTime, DateTime outTime, string message, int Hours)
        {
            this.UserName = user;
            this.ID = TimeSheetId;
            this.Date = date;
            this.TimeSheetIN = inTime;
            this.TimeSheetOUT = outTime;
            this.TotalHours = Hours;
            this.Status = message;

        }

        public List<TimeTrace> TimeTracesList;
    }
}
