//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        
        public int userID { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage ="field is required")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "field is required")]
        public string LastName { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage = "field is required")]
        public string UserName { get; set; }

        [DisplayName("Password")]
        [Compare("Password")]
        [Required(ErrorMessage = "field is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Confirm Password")]
        [Compare("Password")]
        [Required(ErrorMessage = "field is required")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}
